namespace WebApp.Models;

// ErrorViewModel holds request tracing identifiers for displaying error details on the error page.
public class ErrorViewModel
{
    // The request tracking identifier generated by the system.
    public string? RequestId { get; set; }

    // Read-only helper to determine whether to display the RequestId on screen.
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}
